<Project>
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <EnableNETAnalyzers>true</EnableNETAnalyzers>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <WarningsAsErrors>true</WarningsAsErrors>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    </PropertyGroup>

    <ItemGroup>
        <SupportedPlatform Include="windows" />
        <SupportedPlatform Include="linux" />
        <SupportedPlatform Include="mac" />
    </ItemGroup>
</Project>
